require 'rake/clean'
require 'rubygems'
require 'rubygems/package_task'
require 'rake/testtask'

require 'cucumber'
require 'cucumber/rake/task'


spec = eval(File.read('GP.gemspec'))

task :init do
 sh "cp -f test_acceptation/piece.txt.2 .depot.txt"
end

Gem::PackageTask.new(spec) do |pkg|
end


require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test"
  t.libs << "acceptation"
  t.test_files = FileList['test/*_test.rb','test_acceptation/*_test.rb']
  
end

task :default => [:test, :test_acceptation]
